# This file is auto-generated by bearpath.py. Do not edit directly.

from fastapi import APIRouter
from typing import Dict, Any
from .upload import router as upload_router

router = APIRouter()
router.include_router(upload_router, prefix='/upload')

